### ISSUE TITLE
memory module import not working

### ISSUE THREAD

**Issue by dgibb** [dgibb/NES-Emulator-Project#1]
upon sending a valid nes rom to the server the wRamInit function in cpu.js is called which then logs the variable memory to the console. it logs 'undefined' despite there being an import for the memory module at the top of the file.

When trying to run a frame,  functions from the instructionMap array are called which need to access the memory modules functions. there is an error thrown saying

     TypeError: Cannot read property 'writeWord' of undefined
     at Array.BRK (/media/Shared Media/Documents/GitHub/moes-nes/Emulator/cpu.js:

writeWord is a part of the memory module and undefined in the cpu files scope.

memory is also undefined when logged from emulator.js

prgRom which is imported from the same memory.js file into emulator.js seems to be working properly as array contents can be accessed correctly from iNESHandler function

**Comment by Rogibb111** [comment]
The reason you are having this problem is because you have a circular import chain happening. Both memory.js and cpu.js require each other. The way that require works, the import of one file will cause that file to be loaded by node and executed. It looks like memory.js is required first, which then requires in cpu.js. Cpu.js then begins to execute and tries to require memory.js. Since memory.js has hasn't finished it's own execution and been exported (it's still trying to require Cpu.js), the object returned from the require is an empty object.
